[tool.poetry]
name = "mousejiggler"
version = "0.1.0"
description = ""
authors = ["Harry Pan <pan.xingzhi@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pyautogui = "^0.9.54"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
